### ISSUE TITLE
Running client/server

### ISSUE THREAD

**Issue by liamchalk00** [sc1f/perspective-order-book#4]
Hi sc1f! Is this repository still operational? When I run yarn build, yarn start:client, yarn start:server and open http://localhost:8080/, it just shows the loading bar. For the server, Gemini and Websocket seem to connect and for the client, webpack compiles successfully. I have tried running with both perspective-python 2.10.0 and perspective-python 0.10.2. Any help would be appreciated, thanks!

![yarnstartserverclient](https://github.com/sc1f/perspective-order-book/assets/66404407/54d3053c-fdea-4692-a68b-c766449cc286)
![localhost](https://github.com/sc1f/perspective-order-book/assets/66404407/4ae52625-06e1-4e9d-9e08-2233e562a764)

**Comment by sc1f** [comment]
Hi, this repo is no longer active; please look at https://perspective.finos.org/examples/ for up-to-date examples utilizing Perspective. For this issue - you should be able to check the developer console and see if there are any errors logged there - thanks!
